Lab4
StasDen/repoForJava pull request #3
Opened 2022-04-19 18:26 UTC by StasDen

Implemented code of lab4(maven is here)

2022-04-21 16:48 UTC, ChumakAn requested changes

2022-04-21 16:48 UTC, ChumakAn commented on README.md
> +Updated our project
Add descriptive readme please

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/AllOfInsurances.java
> +
remove blank line

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/AllOfInsurances.java
> +
blank line, format your code

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/BrokerManager.java
> +
same here

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/InsuranceManager.java
> +    public String[] advancedTypesOfInsurances = {"vehicle", "health", "casualty", "gap", "life", "burial"};
it's better to use enums

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/InsuranceManager.java
> +        String[] typesOfInsurancesOnSaleInSummer = {"health", "casualty", "gap", "life"};
better to use enum

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/InsuranceManager.java
> +        Arrays.sort(typesOfInsurances);
what about using Streams?

2022-04-21 16:48 UTC, ChumakAn commented on src/main/java/com/lviv/IoT/Insurances.java
> +    public String[] typesOfInsurances = {"vehicle", "health", "casualty"};
better to use enum

2022-04-21 16:48 UTC, ChumakAn commented on src/main/resources/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
it's better not to upload this file on git

2022-04-30 17:55 UTC, StasDen commented
Last commit: implemented the code of lab4*

2022-04-30 17:57 UTC, merged